FROM node:24-alpine

WORKDIR /app

RUN corepack enable && chown node:node /app

USER node

COPY --chown=node:node package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY --chown=node:node . .

EXPOSE 3000

CMD ["pnpm", "start:dev"]
