services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - catfish_node_modules:/app/node_modules

  volumes:
    catfish_node_modules: